images.dir=/usr/local/tomcat/webapps/project/images/

#rides connection config
redis.address=127.0.0.1:6379
redis.address.port=6379
redis.pool.testOnBorrow=true
redis.pool.testOnReturn=false
redis.pool.testWhileIdle=false
redis.pool.maxIdle=1000
redis.pool.minIdle=150
redis.pool.maxActive=1000
redis.pool.maxWait=3000
redis.pool.timeout=3000
redis.pool.numTestsPerEvictionRun=0
redis.pool.timeBetweenEvictionRunsMillis=0
redis.pool.minEvictableIdleTimeMillis=0

backstage_url=http://127.0.0.1/admin
dm_url=http://127.0.0.1
#dubbo connection config
dubbo.application.name=admin
dubbo.registry.protocol=zookeeper
dubbo.registry.address=127.0.0.1:2181

#database connection config
jdbc.driver = com.mysql.jdbc.Driver
jdbc.url = jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8
jdbc.username = mall
jdbc.password = XXKytcACPX3GbdsH

#hibernate config
hibernate.dialect = org.hibernate.dialect.MySQLDialect
hibernate.show_sql = true
hibernate.format_sql = true
hibernate.hbm2ddl.auto = update


email.host=smtp.gmail.com
email.port=587
email.username=linnana5885858@gmail.com
email.password=oxkw vxyl tufz kcwm
email.from=linnana5885858@gmail.com

# email.host=smtp.office365.com
# email.port=587
# email.username=sendtoautotocodesendto@outlook.com
# email.password=1FW*VDZ#eN!
# email.from=sendtoautotocodesendto@outlook.com
#email.host=smtp.gmail.com
#email.username=
#email.password=
#email.from=smtp.gmail.com
