http.server.host=https://tiktok898.com/images/
images.dir=/usr/local/tomcat/webapps/project/images/
admin_url=https://tiktok898.com/admin
web_url=https://tiktok898.com/wap/
admin_code_url=https://tiktok898.com/admin
mall.default.time.zone=GMT+8
