http.server.host=https://shop2.woshop.shop/images/
images.dir=/usr/local/tomcat/webapps/project/images/
web_url=https://shop2.woshop.shop/wap/
admin_code_url=https://shop2.woshop.shop/894732342
mall.default.time.zone=GMT+8
